stages:
  - deploy

main:
  tags:
    - botanalytics # Use the correct runner
  stage: deploy
  script:
  - /usr/bin/rsync --delete
    --exclude=.env
    --exclude=.git
    -a $CI_PROJECT_DIR/ /opt/dashboard/ # Copy the data into place
  
  - echo 'Installing dependencies...'
  - npm install

  - echo 'Building the application...'
  - npm run build

  - echo 'Populating environment variables...'

  - echo 'Reloading the app with PM2...'
  - pm2 reload chatbot-metrics-dashboard

  - echo 'Deployment finished successfully!'

  # Define rules for when this job should run.
  rules:
    # Only run this job on pushes to the 'main' branch.
    - if: '$CI_COMMIT_BRANCH == "main"'
